env:
- TEST_WITH_NETWORK=1

language: perl
perl:
    - "5.28"
      #- "5.26"
      #- "5.24"
      #- "5.22"
    - "5.20"
    - "5.16"

before_install:
    # Install configure-time dependencies
    - cpanm --quiet --notest Devel::CheckLib Module::Install Module::Install::XSUtil

    # Install compile-time dependencies
    - sudo apt-get install -y libidn11-dev

before_script:
    - perl -E 'say "qq(@INC)";
    - find $TRAVIS_HOME -name 'CheckLib*'
