---
abstract: 'Perl wrapper for the ldns DNS library.'
author:
  - 'Mattias P <mattias.paivarinta@iis.se>'
build_requires:
  Devel::CheckLib: '0.4'
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.59
  JSON::PP: 0
  Test::Fatal: 0
  Test::Simple: 1.302015
configure_requires:
  Devel::CheckLib: '0.4'
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.59
  ExtUtils::ParseXS: 3.18
  Module::Install: 1.19
  Module::Install::XSUtil: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Zonemaster-LDNS
no_index:
  directory:
    - inc
    - t
requires:
  MIME::Base64: 0
  XSLoader: 0.02
  perl: 5.14.0
resources:
  bugtracker: https://github.com/zonemaster/zonemaster-ldns/issues
  license: http://opensource.org/licenses/bsd-license.php
  repository: https://github.com/zonemaster/zonemaster-ldns
version: 2.0.0
